name: realistic_button
description: "Aesthetic, realistic and on/off status LED indicator button package for Flutter"
version: 0.0.1
homepage: https://reposis.com
repository: https://github.com/reposis/realistic_button
issue_tracker: https://github.com/reposis/realistic_button/issues

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0